### ISSUE TITLE
Simplify install

### ISSUE THREAD

**Issue by colombod** [pi-top/pi-top-4-.NET-Core-API#10]
* ~Remove unpacking of opencv~
* [x] Document app requirements when using camera model (use the nuget package with runtimes)
* [x] Remove python setup for jupyter and make it a separate script
* ~Issue lts .net as part of os?~
* ~remove repo cloning and local build~

**Comment by m-roberts** [comment]
> * Remove unpacking of opencv

I think that this is captured in #3 

> * Document app requirements when using camera model (use the nuget package with runtimes)

What is a rough outline of what needs to be documented here?

> * Remove python setup for jupyter and make it a separate script

Yep.

> * Issue LTS .NET as part of os?

I think that we should keep it as it is for now until we can understand the value proposition for our customers' use-cases.

> * Remove repo cloning and local build

If I've understood this correctly, I think that some of the discussion for this is also captured in #3. This can come later, once we have "wired everything up".
