### ISSUE TITLE
Pack bot for execution on pi-top

### ISSUE THREAD

**Issue by colombod** [pi-top/pi-top-4-.NET-Core-API#6]
https://github.com/CodeConversations/CodeConversations/blob/master/BuildCodeBot.md

**Comment by m-roberts** [comment]
Does this mean some sort of install script to deploy it onto any pi-top? What should we do about packaging up secrets? Does that include an `ngrok` configuration?

**Comment by m-roberts** [comment]
Migrated to more appropriate repo.
